os: linux
language: cpp
dist: bionic
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libmosquitto-dev
script:
  - mkdir build && cd build
  - cmake .. -DUNITTESTS=on
  - make -j8
  - for TEST in $(ls tests/unit/unit_*); do ${TEST}; done
